apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesample
spec:
  replicas: 3
  selector:
    matchLabels:
      component: kubernetesample
  template:
    metadata:
      labels:
        component: kubernetesample
    spec:
      containers:
        - name: kubernetesample
          image: cemyldzz/kubernetesample:1.3
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: SA_PASSWORD
            - name: ASPNETCORE_ENVIRONMENT
              value: Development