apiVersion: v1
kind: Service
metadata:
  name: kubernetesample-server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: kubernetesample
  ports:
    - port: 80
      targetPort: 80