apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetesample
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: kubernetesample-server-cluster-ip-service
              servicePort: 80